apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Core Infrastructure
  - core/storage
  - core/ingress-nginx
  - core/cert-manager
  - core/ingress
  
  # Bootstrap
  - bootstrap/argocd
  
  # Observability
  - observability
  
  # Automation
  - automation
