apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: n8n
  namespace: automation
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`n8n.luigi99.cloud`)
      kind: Rule
      services:
        - name: n8n
          port: 5678
  tls:
    certResolver: letsencrypt