apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: n8n
  namespace: automation
spec:
  serviceName: n8n
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      containers:
      - name: n8n
        image: n8nio/n8n:1.114.3
        ports:
        - containerPort: 5678
        env:
        - name: N8N_SMTP_USER
          valueFrom:
            secretKeyRef:
              name: n8n-secret
              key: N8N_SMTP_USER
        - name: N8N_SMTP_PASS
          valueFrom:
            secretKeyRef:
              name: n8n-secret
              key: N8N_SMTP_PASS
        - name: N8N_SMTP_SENDER
          valueFrom:
            secretKeyRef:
              name: n8n-secret
              key: N8N_SMTP_SENDER
        envFrom:
        - configMapRef:
            name: n8n-config
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - name: n8n-storage
          mountPath: /home/node/.n8n
  volumeClaimTemplates:
  - metadata:
      name: n8n-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: longhorn
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: n8n
  namespace: automation
spec:
  selector:
    app: n8n
  type: ClusterIP
  ports:
  - port: 5678
    targetPort: 5678
