apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: n8n-postgresql
  namespace: automation
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: n8n-postgresql
  template:
    metadata:
      labels:
        app: n8n-postgresql
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: postgres
          image: pgvector/pgvector:pg16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: n8n-postgresql-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: n8n-postgresql-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: n8n-postgresql-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: n8n-postgresql-storage
              mountPath: /var/lib/postgresql/data
              subPath: pgdata
  volumeClaimTemplates:
    - metadata:
        name: n8n-postgresql-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: longhorn
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: n8n-postgresql
  namespace: automation
spec:
  selector:
    app: n8n-postgresql
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
