apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast-ssd
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: rancher.io/local-path
parameters:
  nodePath: /var/lib/rancher/k3s/storage
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: bulk-hdd
provisioner: rancher.io/local-path
parameters:
  nodePath: /data/k3s-storage
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
