apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: observability
data:
  otel-collector-config: |
    receivers:
      otlp:
        protocols:
          http:
            endpoint: 0.0.0.0:4318

      prometheus:
        config:
          scrape_configs:
            - job_name: 'argocd-metrics'
              static_configs:
                - targets: ['argocd-metrics.argocd.svc.cluster.local:8082']
            - job_name: 'argocd-server-metrics'
              static_configs:
                - targets: ['argocd-server-metrics.argocd.svc.cluster.local:8083']
            - job_name: 'argocd-repo-server-metrics'
              static_configs:
                - targets: ['argocd-repo-server.argocd.svc.cluster.local:8084']
            - job_name: 'argocd-applicationset-controller'
              static_configs:
                - targets: ['argocd-applicationset-controller.argocd.svc.cluster.local:8080']
    
    processors:
      batch:
    
    exporters:
      prometheus:
        endpoint: 0.0.0.0:8889
        resource_to_telemetry_conversion:
          enabled: true
    
      otlphttp/loki:
        endpoint: http://loki:3100/otlp
    
      otlphttp/tempo:
        endpoint: http://tempo:4318
    
    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
    
    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp/tempo]
        metrics:
          receivers: [otlp, prometheus]
          processors: [batch]
          exporters: [prometheus]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp/loki]
