apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  namespace: observability
data:
  tempo.yaml: |-
    stream_over_http_enabled: true
    
    server:
      http_listen_port: 3200
    
    distributor:
      receivers:
        otlp:
          protocols:
            http:
              endpoint: 0.0.0.0:4318
    
    ingester:
      trace_idle_period: 5s
      flush_check_period: 5s
      max_block_duration: 1m
    
    compactor:
      compaction:
        block_retention: 168h
        compaction_window: 1h
    
    storage:
      trace:
        backend: local
        wal:
          path: /var/tempo/wal
        local:
          path: /var/tempo/blocks
    
    metrics_generator:
      storage:
        path: /var/tempo/generator/wal
        remote_write:
          - url: http://prometheus:9090/api/v1/write
            send_exemplars: true
      processor:
        local_blocks:
          flush_to_storage: true
    
    overrides:
      defaults:
        metrics_generator:
          processors: [service-graphs, span-metrics]
