apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bookstack
  namespace: wiki
spec:
  serviceName: bookstack
  replicas: 1
  selector:
    matchLabels:
      app: bookstack
  template:
    metadata:
      labels:
        app: bookstack
    spec:
      containers:
      - name: bookstack
        image: lscr.io/linuxserver/bookstack:latest
        ports:
        - containerPort: 80
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        envFrom:
        - configMapRef:
            name: bookstack-config
        - secretRef:
            name: bookstack-secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: bookstack-storage
          mountPath: /config
  volumeClaimTemplates:
  - metadata:
      name: bookstack-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: bulk-hdd
      resources:
        requests:
          storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: bookstack
  namespace: wiki
spec:
  selector:
    app: bookstack
  type: ClusterIP
  ports:
  - port: 6875
    targetPort: 80
